<?xml version="1.0" encoding="utf-8"?><Database Name="SpamBase" Class="CustomSmtpClientsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=SpamBase;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="MailSendLibrary.Properties.Settings" SettingsPropertyName="SpamBaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CustomSmtpClients" Member="CustomSmtpClient">
    <Type Name="CustomSmtpClient">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SmtpServer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>